[phases.setup]
# Define nix packages to install
# Incluir solo nodejs_20, npm debería venir incluido
nixPkgs = ["nodejs_20"]

[phases.install]
# Define commands to run during the install phase
cmds = ["npm install"]

[phases.build]
# Define commands to run during the build phase
# No necesitamos un build step explícito si no transpilamos código
# cmds = ["npm run build"]

[start]
# Define the command to start the application
cmd = "node server.js" 